import logging
import os
from pathlib import Path
from typing import Optional

import boto3
from botocore.exceptions import BotoCoreError, ClientError
from dotenv import load_dotenv


LOGGER = logging.getLogger(__name__)


def load_environment() -> None:
    """
    Load environment variables from .env if present.
    """
    load_dotenv()


def get_bucket_name(explicit_bucket: Optional[str] = None) -> str:
    """
    Resolve the S3 bucket name.

    Prefers an explicit argument, otherwise uses S3_BUCKET from the environment.
    """
    bucket = explicit_bucket or os.getenv("S3_BUCKET")
    if not bucket:
        raise RuntimeError(
            "S3 bucket name not provided. "
            "Set S3_BUCKET in your .env or pass bucket explicitly."
        )
    return bucket


def get_logs_local_dir() -> Path:
    """
    Return the local directory where ingestion Python scripts write logs.

    Default: logs/ingestion (relative to project root), override with LOGS_INGESTION_DIR.
    """
    base_dir = os.getenv("LOGS_INGESTION_DIR", "logs/ingestion")
    return Path(base_dir)


def get_logs_s3_prefix() -> str:
    """
    Return the S3 prefix for ingestion logs.

    This is fixed to 'logs/ingestion' to align with the requested layout.
    """
    return "logs/ingestion"


def configure_logging(verbose: bool = False) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(levelname)s %(name)s - %(message)s",
    )


def upload_logs_to_s3(
    bucket: Optional[str] = None,
    verbose: bool = False,
) -> None:
    """
    Upload log files generated by ingestion Python scripts to S3.

    - Reads credentials, region, and S3 bucket name from .env
      (S3_BUCKET, AWS_REGION / AWS_DEFAULT_REGION, etc.).
    - Looks for log files under LOGS_INGESTION_DIR env var or 'logs/ingestion' by default.
    - Uploads all regular files in that directory (non-recursive) to:
        s3://<bucket>/logs/ingestion/<filename>
    """
    load_environment()
    configure_logging(verbose=verbose)

    bucket_name = get_bucket_name(bucket)
    logs_dir = get_logs_local_dir()
    s3_prefix = get_logs_s3_prefix().rstrip("/")

    if not logs_dir.exists() or not logs_dir.is_dir():
        LOGGER.info("Logs directory does not exist or is not a directory: %s", logs_dir)
        return

    session = boto3.session.Session()
    s3_client = session.client("s3")

    LOGGER.info(
        "Uploading ingestion logs from %s to s3://%s/%s/",
        logs_dir.resolve(),
        bucket_name,
        s3_prefix,
    )

    uploaded = 0
    failed = 0

    for entry in sorted(logs_dir.iterdir()):
        if not entry.is_file():
            continue

        key = f"{s3_prefix}/{entry.name}"
        s3_path = f"s3://{bucket_name}/{key}"

        try:
            LOGGER.info("Uploading log file %s -> %s", entry, s3_path)
            s3_client.upload_file(str(entry), bucket_name, key)
            uploaded += 1
        except (ClientError, BotoCoreError) as exc:
            failed += 1
            LOGGER.error("Failed to upload log file %s: %s", entry, exc)

    LOGGER.info(
        "Completed log upload. Uploaded=%d Failed=%d",
        uploaded,
        failed,
    )

    if failed > 0:
        raise RuntimeError(f"Failed to upload {failed} log file(s) to S3 bucket {bucket_name}")


if __name__ == "__main__":
    # Simple CLI entrypoint: python -m ingestion.upload_logs
    upload_logs_to_s3()

